name: CI/CD Pipeline Pharmacy Central System

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check if main branch was updated
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "Main branch updated. Proceeding with the build and deploy steps."
          else
            echo "Main branch not updated. Skipping build and deploy steps."
            exit 0
          fi
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build and push Docker image
        run: |
          docker build -t adrianovolter/front-pharmacy .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push adrianovolter/front-pharmacy:latest
